version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
    volumes:
      - ~/jenkins/var/jenkins_home:/var/jenkins_home

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444